# -*- coding: utf-8 -*-
"""pix2pix_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1prb4RcGjgsweVTZF5G1URcqMxKSMX4Sk
"""

#!pip3 install scipy==1.1.0
#!pip install texttable

#from google.colab import drive
#drive.mount('/gdrive')
# %cd /gdrive

import configparser
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt
from six.moves import cPickle
import os
import matplotlib.colors as mcolors
from mpl_toolkits.axes_grid1 import make_axes_locatable
import statistics as stats
import glob
from texttable import Texttable

x=np.load("X_test.npy")
y=np.load("y_test.npy")
preds=np.load("preds.npy")
prob=np.load("preds_proba.npy")

#classes=[2,4,5,6,8,13]
classes=[1]
filterid={1:0,2:1,4:2,5:3,6:4,8:5,13:6}
pd={1:'EW',2:'EA',4:'RRab',5:'RRc',6:'RRd',8:'RSCVn',13:'LPV'}

dmints = [-8,-5,-3,-2.5,-2,-1.5,-1,-0.5,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.5,1,1.5,2,2.5,3,5,8]
dtints = [0,1.0/145,2.0/145,3.0/145,4.0/145,1.0/25,2.0/25,3.0/25,1.5,2.5,3.5,4.5,5.5,7,10,20,30,60,90,120,240,600,960,2000,4000]

xloc=np.arange(25)
yloc=np.arange(23)
yloc=yloc[::-1]
for i in range(len(dtints)):
    dtints[i]=round(dtints[i],3)
yloc=yloc-0.5
xloc=xloc-0.5

thres=np.where(prob>=0.8)
ind_thres=thres[0]
class_thres=thres[1]

##os.mkdir("keras-vis/dmdt_sqrt")

for i in range(len(classes)):
   # This is the output node we want to maximize.
   filter_idx = filterid[classes[i]]
   os.mkdir("keras-vis/dmdt_sqrt/"+pd[classes[i]]+"/")
   x_ind=np.where(class_thres==filter_idx)[0]
   #init=np.where(ind_thres[x_ind]==8882)[0][0]
   init=0
   for ii in range(init,x_ind.shape[0]):
       #image=x[ind_thres[x_ind[ii]]].transpose((1,2,0))
       image=x[ind_thres[x_ind[ii]]]
       plt.figure()
       plt.imshow(np.sqrt(image[:,:,0]))
       plt.axis('off')
       plt.savefig("keras-vis/dmdt_sqrt/"+pd[classes[i]]+"/"+str(ind_thres[x_ind[ii]])+".png", bbox_inches='tight', transparent="True", pad_inches=0)
       plt.close()
